//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Ext.rc
//
#define IDB_FILE                        101
#define IDB_DIR2                        102
#define IDB_DIR                         103
#define DB_SETUP2                       109
#define IDC_MOVE                        110
#define DB_EDIT                         111
#define IDD_EDITTEXT                    112
#define IDST_OBJNAME                    128
#define IDST_AUTHOR                     129
#define IDST_COPYRIGHT                  130
#define IDST_COMMENT                    131
#define IDST_HTTP                       132
#define M_ACTIONS_MYACTION              200
#define M_CONDITIONS_MYCONDITION        300
#define M_EXPRESSIONS_MYEXPRESSION      400
#define M_PARAM_MYACTION                500
#define M_PARAM_MYCONDITION             501
#define M_PARAM_MYEXPRESSION            502
#define IDS_COLUMN                      503
#define IDS_COLUMNITEM                  504
#define IDS_ACTION_INSERTITEM           505
#define IDS_ACTION_SETSUBITEM           506
#define IDS_ACTION_INSERTCOLUMN         507
#define IDS_ACTION_DELETEITEM           508
#define IDS_ACTION_DELETECOLUMN         509
#define IDS_ACTION_SORTASC              510
#define IDS_ACTION_SORTDESC             511
#define IDS_ACTION_SETBACKCOLOR         512
#define IDS_ACTION_SETTEXTCOLOR         513
#define IDS_ACTION_SAVE                 514
#define IDS_ACTION_LOAD                 515
#define IDS_PARAM_ENTERITEM             516
#define IDS_PARAM_ENTERNAME             517
#define IDS_PARAM_ENTERSUBITEM          518
#define IDS_PARAM_ENTERCOLUMN           519
#define IDS_PARAM_ENTERSIZE             520
#define IDS_CONDITION_LCLICK            521
#define IDS_CONDITION_RCLICK            522
#define IDS_CONDITION_DBLCLICK          523
#define IDS_CONDITION_COLUMNCLICK       524
#define IDS_EXPRESSION_ITEMCLICK        525
#define IDS_EXPRESSION_COLUMNCLICK      526
#define IDS_EXPRESSION_ITEMATCOORD      527
#define IDS_EXPRESSION_COLUMNATCOORD    528
#define IDS_EXPRESSION_TEXT             529
#define IDS_PARAM_X                     530
#define IDS_PARAM_Y                     531
#define IDS_PARAM_ITEM                  532
#define IDS_PARAM_COLUMN                533
#define IDS_PARAM_ENTERALIGN            534
#define IDS_ACTION_EDIT                 535
#define IDS_EXPRESSION_GETFIRSTSEL      536
#define IDS_EXPRESSION_GETNEXTSEL       538
#define IDS_ACTION_SHOW                 539
#define IDS_ACTION_HIDE                 540
#define IDS_ACTION_SETWIDTH             541
#define IDS_ACTION_SETHEIGHT            542
#define IDS_EXPRESSION_GETWIDTH         543
#define IDS_EXPRESSION_GETHEIGHT        544
#define IDS_CONDITION_ISENABLED         545
#define IDS_CONDITION_ISVISIBLE         546
#define IDS_ACTION_ENABLE               547
#define IDS_ACTION_DISABLE              548
#define IDS_EXPRESSION_GETNCOLUMNS      549
#define IDS_EXPRESSION_GETNLINES        550
#define IDS_PARAM_SETCOLUMNSIZE         551
#define IDS_ACTION_SETCOLUMN            552
#define IDS_ACTION_CLEARALL             553
#define IDS_ACTION_SAVEARRAY            554
#define IDS_ACTION_LOADARRAY            555
#define IDS_ACTION_SAVEASCII            556
#define IDS_ACTION_LOADASCII            557
#define IDS_PARAM_SAVEDIGITS            558
#define IDS_EXPRESSION_GETIDENTIFIER    559
#define IDS_EXPRESSION_GETLINE          560
#define IDS_PARAM_DELIMITEUR            561
#define IDS_PARAM_ENTERALIGNSET         562
#define IDS_ACTION_CLEARALLLINES        563
#define IDS_EXPRESSION_GETCOLUMNSIZE    564
#define IDS_ACTION_SELECTLINE           565
#define IDS_ACTION_UNSELECTLINE         566
#define IDS_PARAM_SEARCHSTRING          567
#define IDS_PARAM_SEARCHCOLUMN          568
#define IDS_PARAM_SEARCHCASE            569
#define IDS_PARAM_SEARCHMODE            570
#define IDS_ACTION_SEARCH               571
#define IDS_ACTION_SEARCHNEXT           572
#define IDS_EXPRESSION_XLEFT            573
#define IDS_EXPRESSION_GETXLEFT         573
#define IDS_EXPRESSION_YTOP             574
#define IDS_EXPRESSION_GETYTOP          574
#define IDS_EXPRESSION_XRIGHT           575
#define IDS_EXPRESSION_GETXRIGHT        575
#define IDS_EXPRESSION_YBOTTOM          576
#define IDS_EXPRESSION_GETYBOTTOM       576
#define IDS_EXPRESSION_GETNSELLINES     577
#define IDS_EXPRESSION_GETNTHSELLINE    578
#define IDS_PROP_ALIGN                  579
#define IDS_PROP_ALIGNCOMBO             580
#define IDS_PROP_OPTIONS                581
#define IDS_PROP_FULLROW                582
#define IDS_PROP_HEADERS                583
#define IDS_PROP_CLICKABLE              584
#define IDS_PROP_SCROLL                 585
#define IDS_PROP_GRID                   586
#define IDS_PROP_MULTIPLE               587
#define IDS_PROP_ALWAYS                 588
#define IDS_PROP_WINDOW                 589
#define IDS_PROP_VISIBLE                590
#define IDS_PROP_BORDER                 591
#define IDS_PROP_THICK                  592
#define IDS_PROP_3D                     593
#define IDS_PROP_BACKGROUND             594
#define IDS_PROP_BCKCOLOR               595
#define IDS_PROP_ALIGNCOMBO_INFO        596
#define IDS_PROP_FULLROW_INFO           597
#define IDS_PROP_HEADERS_INFO           598
#define IDS_PROP_CLICKABLE_INFO         599
#define IDS_PROP_SCROLL_INFO            600
#define IDS_PROP_GRID_INFO              601
#define IDS_PROP_MULTIPLE_INFO          602
#define IDS_PROP_ALWAYS_INFO            603
#define IDS_PROP_VISIBLE_INFO           604
#define IDS_PROP_BORDER_INFO            605
#define IDS_PROP_THICK_INFO             606
#define IDS_PROP_STATIC                 606
#define IDS_PROP_3D_INFO                607
#define IDS_PROP_STATIC_INFO            607
#define IDS_PROP_BCKCOLOR_INFO          608
#define IDS_PROP_CLIENT                 608
#define IDS_PROP_CONTENT                609
#define IDS_PROP_CLIENT_INFO            609
#define IDS_PROP_EDITCONTENT            610
#define IDS_EXPRESSION_GETTEXT          610
#define IDS_PROP_EDITCONTENT_INFO       611
#define IDS_ACTION_SORTNUMBER           612
#define IDS_EXPPARAM_X                  613
#define IDS_EXPPARAM_Y                  614
#define IDS_EXPPARAM_LINE               615
#define IDS_EXPPARAM_COLUMN             616
#define IDS_PROP_STYLES                 617
#define IDS_PROP_STYLES_INFO            618
#define IDS_PROP_BACKCOLOR              619
#define IDS_PROP_BACKCOLOR_INFO         620
#define IDS_PROP_FONTCOLOR              621
#define IDS_PROP_FONTCOLOR_INFO         622
#define IDS_PROP_TEXT                   623
#define IDS_PROP_TEXT_INFO              624
#define IDS_LEFT                        625
#define IDS_CENTER                      626
#define IDS_RIGHT                       627
#define IDS_PROP_BORDERGROUP            628
#define IDS_PROP_SINGLELINE             629
#define IDS_PROP_SINGLELINE_INFO        630
#define IDS_PROP_VCENTER                631
#define IDS_PROP_VCENTER_INFO           632
#define IDS_PROP_PATHELLIPSIS           633
#define IDS_PROP_PATHELLIPSIS_INFO      634
#define IDS_PROP_ENDELLIPSIS            635
#define IDS_PROP_ENDELLIPSIS_INFO       636
#define IDS_ACTION_SETTEXT              637
#define IDS_SETTEXT                     638
#define IDS_SETWIDTH                    639
#define IDS_SETHEIGHT                   640
#define ID_OK                           1019
#define IDC_LIST                        1042
#define IDC_CHECK_EDITLABELS            1043
#define IDC_CHECK_FULLROWSELECT         1043
#define IDC_CHECK_COLUMNHEADERS         1044
#define IDC_CHECK_NOSCROLL              1045
#define IDC_CHECK_SCROLLBARS            1045
#define IDC_CHECK_SHOWSELALWAYS         1046
#define IDC_CHECK_MULTIPLESELECTIONS    1047
#define IDC_CHECK_GRIDLINES             1048
#define IDC_CHECK_BORDER                1049
#define IDC_CHECK_VISIBLEATSTART        1050
#define IDC_BUTTON_NEWITEM              1051
#define IDC_BUTTON_DELETEITEM           1052
#define IDC_BUTTON_DELETECOLUMN         1053
#define IDC_BUTTON_NEWCOLUMN            1054
#define IDC_EDIT_COLUMN                 1055
#define IDC_BUTTON_TEXTCOLOR            1056
#define IDC_BUTTON_BACKCOLOR            1057
#define IDC_RADIO_LEFT                  1058
#define IDC_RADIO_CENTER                1059
#define IDC_RADIO_RIGHT                 1060
#define IDC_CHECK_NOSORTHEADER          1061
#define IDC_STATIC_PROONLY              1062
#define IDC_CHECK_THICKFRAME            1063
#define IDC_CHECK_3DBORDER              1064
#define IDC_BUTTON_FONT                 1065
#define IDC_ENTERTEXTEDIT               1067
#define MN_ACTIONS                      20000
#define MN_CONDITIONS                   20001
#define MN_EXPRESSIONS                  20002
#define DB_SETUP                        20003
#define ID_HELP                         20004
#define IDD_EDITTEXTMULTI               20004
#define IDMN_ACTION_SETTEXT             25000
#define IDMN_ACTION_SHOW                25001
#define IDMN_ACTION_HIDE                25002
#define IDMN_ACTION_SETWIDTH            25003
#define IDMN_ACTION_SETHEIGHT           25004
#define IDMN_ACTION_SETTEXTCOLOR        25005
#define IDMN_ACTION_SETBACKCOLOR        25006
#define IDMN_CONDITIONS_LCLICK          26000
#define IDMN_CONDITIONS_RCLICK          26001
#define IDMN_CONDITIONS_DBLCLICK        26002
#define IDMN_CONDITIONS_ISVISIBLE       26004
#define IDMN_EXPRESSIONS_GETWIDTH       27000
#define IDMN_EXPRESSIONS_GETHEIGHT      27001
#define IDMN_EXPRESSIONS_GETTEXT        27002
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        113
#define _APS_NEXT_COMMAND_VALUE         40154
#define _APS_NEXT_CONTROL_VALUE         1068
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
